Repository crocoder-dev/monorepo, pull requests merged in 2023-03, with the labels that each got.

#50 Feat/how to clone rewrite
  .cm/gitstream.cm
  apps/company-website/src/content/images/blogs/how-to-clone-object-in-javascript.png
  apps/company-website/src/pages/blog/how-to-clone-object-in-javascript.mdx
  apps/company-website/vercel.json
  package-lock.json
Labels: cm-changes

#55 Feat/node docker image blog
  apps/company-website/index.html
  apps/company-website/src/components/Blog/BlogLink/index.jsx
  apps/company-website/src/components/Blog/ContentTable/index.jsx
  apps/company-website/src/components/Code/index.jsx
  apps/company-website/src/content/images/blogs/map-filter-reduce-exercises.png
  apps/company-website/src/content/images/blogs/map-filter-reduce.png
  apps/company-website/src/content/images/blogs/node-docker-image.png
  apps/company-website/src/pages/blog/how-to-clone-object-in-javascript.mdx
  apps/company-website/src/pages/blog/map-filter-reduce-exercises.mdx
  apps/company-website/src/pages/blog/node-docker-image.mdx
  package-lock.json
Labels: 5 min review, deleted-files

#56 Feat/backend
  .vscode/settings.json
  apps/news/app/api/post/route.ts
  apps/news/app/components/nav.tsx
  apps/news/app/components/post-item.tsx
  apps/news/app/components/posts.tsx
  apps/news/app/head.tsx
  apps/news/app/layout.tsx
  apps/news/app/page.tsx
  apps/news/env/schema.mjs
  apps/news/package.json
  apps/news/pages/api/create-post.ts
  apps/news/pages/api/example.ts
  apps/news/public/media/nav-options.svg
  apps/news/styles/globals.css
  package-lock.json
  package.json
  packages/db/prisma/schema.prisma
  packages/edge-db/closestDatabase.ts
  packages/edge-db/db.ts
Labels: 10 min review, deleted-files

#60 Feat/drizzle
  .env.example
  .github/workflows/pr.yml
  apps/news/app/api/post/route.ts
  apps/news/app/components/post-item.tsx
  apps/news/app/components/posts.tsx
  apps/news/app/page.tsx
  apps/news/next.config.mjs
  apps/news/package.json
  package-lock.json
  packages/db/.gitignore
  packages/db/db.ts
  packages/db/package.json
  packages/db/schema.ts
  packages/db/tsconfig.json
Labels: 10 min review

#63 Feat/new design
  apps/news/app/api/post/route.ts
  apps/news/app/components/post-item.tsx
  apps/news/app/components/posts.tsx
Labels: 5 min review

#65 Feat/blog post agile misuse
  apps/company-website/src/content/images/blogs/misusing-agile-is-holding-your-team-back.png
  apps/company-website/src/pages/blog/misusing-agile-is-holding-your-team-back.mdx
Labels: 1 min review
