Repository crocoder-dev/monorepo, pull requests merged in 2023-04, with the labels that each got.

#67 feat: add simple analytics
  apps/news/app/layout.tsx
  apps/news/next.config.mjs
Labels: 1 min review

#66 Feat/news editions
  apps/news/app/api/edition/route.ts
  apps/news/app/api/post/route.ts
  apps/news/app/components/post-item.tsx
  apps/news/app/components/posts.tsx
  apps/news/app/edition/[id]/page.tsx
  apps/news/app/page.tsx
  package-lock.json
  package.json
  packages/db/package.json
  packages/db/schema.ts
Labels: 5 min review

#68 feat: random upgrades
  .env.example
  apps/news/app/[slug]/page.tsx
  apps/news/app/api/edition/route.ts
  apps/news/app/api/post/route.ts
  apps/news/app/page.tsx
  package-lock.json
  packages/db/.gitignore
  packages/db/drizzle.config.json
  packages/db/migrations/0000_wise_starjammers.sql
  packages/db/migrations/meta/0000_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/package.json
  packages/db/schema.ts
Labels: 5 min review, deleted-files

#70 Feat/news changes
  apps/news/app/[slug]/page.tsx
  apps/news/app/api/post/route.ts
  apps/news/app/components/nav.tsx
  apps/news/app/components/post-item.tsx
  apps/news/app/components/posts.tsx
  apps/news/app/head.tsx
  apps/news/app/layout.tsx
  apps/news/app/page.tsx
  apps/news/env/schema.mjs
  apps/news/public/android-chrome-192x192.png
  apps/news/public/android-chrome-512x512.png
  apps/news/public/apple-touch-icon.png
  apps/news/public/favicon-16x16.png
  apps/news/public/favicon-32x32.png
  apps/news/public/favicon.ico
  package-lock.json
Labels: 10 min review, deleted-files

#72 Feat: added dark theme to project
  apps/news/app/components/nav.tsx
  apps/news/app/components/post-item.tsx
  apps/news/app/components/posts.tsx
  apps/news/app/components/theme-switch.tsx
  apps/news/app/head.tsx
  apps/news/app/layout.tsx
  apps/news/tailwind.config.cjs
Labels: 5 min review

#73 Feat/prompt fix
  apps/news/app/api/post/route.ts
Labels: 1 min review

#76 Feat/clerk auth
  apps/admin/.gitignore
  apps/admin/.vscode/settings.json
  apps/admin/README.md
  apps/admin/app/api/auth.ts
  apps/admin/app/layout.tsx
  apps/admin/app/page.tsx
  apps/admin/app/sign-in/page.tsx
  apps/admin/app/sign-up/page.tsx
  apps/admin/env/client.mjs
  apps/admin/env/schema.mjs
  apps/admin/env/server.mjs
  apps/admin/middleware.ts
  apps/admin/next.config.js
  apps/admin/package.json
  apps/admin/postcss.config.js
  apps/admin/public/favicon.ico
  apps/admin/styles/globals.css
  apps/admin/tailwind.config.js
  apps/admin/tsconfig.json
  package-lock.json
Labels: 5 min review

#82 Feat/rss feed
  apps/news/app/feed/route.ts
  apps/news/content/site-config.json
  apps/news/package.json
  package-lock.json
Labels: 5 min review

#83 feat: when generating an emojii, delete unnecesary text
  apps/news/app/api/post/route.ts
Labels: 1 min review

#84 Feat: added description and abstract to edition table
  apps/news/app/api/description/route.ts
  packages/db/migrations/0001_fluffy_mystique.sql
  packages/db/migrations/meta/0001_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/package.json
  packages/db/schema.ts
Labels: 5 min review
